# Generated by Django 5.2.7 on 2025-11-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_accessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
